# Generated by Django 6.0.5 on 2026-05-15 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("models", "12587_move_default_value_to_node_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="VersionedResource",
            fields=[
                (
                    "resourceinstance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="models.resourceinstance",
                    ),
                ),
                ("resource_group_id", models.CharField(max_length=255)),
                ("major_version", models.IntegerField(default=0)),
                ("minor_version", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "versioned_resource",
                "managed": True,
            },
        ),
    ]
